name: Setup
description: 'Setup development environment for Guillotine'
runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Install cbindgen
      run: |
        cargo install --locked cbindgen
      shell: bash

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.2.13

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.0

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install native dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          libglib2.0-dev \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev