[workspace]
resolver = "2"
members = ["src/compilers", "src/bn254_wrapper", "src/revm_wrapper", "benches/evm-bench-rust"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
# Optimize for size by default (smallest flag)
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[profile.release-fast]
# Optimize for speed when fastest flag is used
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"