version: '3.8'

services:
  # Main fuzz testing service
  fuzz:
    build:
      context: ../../..
      dockerfile: src/evm2/fuzz/Dockerfile
    image: guillotine-evm2-fuzz
    container_name: evm2-fuzzer
    volumes:
      # Mount source code for live updates
      - ../../../:/app:ro
    working_dir: /app/src
    command: zig test evm2/fuzz/evm2_fuzz.zig --fuzz
    environment:
      # Set fuzz testing duration (in seconds)
      - FUZZ_DURATION=${FUZZ_DURATION:-300}
    networks:
      - fuzz-network

  # Run all fuzz tests with customizable duration
  fuzz-all:
    extends: fuzz
    command: zig build test -- --fuzz=${FUZZ_DURATION:-300}s

  # Run specific fuzz test
  fuzz-single:
    extends: fuzz
    command: zig test ${FUZZ_TEST:-evm2/fuzz/evm2_fuzz.zig} --fuzz

  # Continuous fuzzing with restart on failure
  fuzz-continuous:
    extends: fuzz
    restart: unless-stopped
    command: >
      sh -c "while true; do
        echo 'Starting fuzz run at' $$(date);
        zig test evm2/fuzz/evm2_fuzz.zig --fuzz=3600s || true;
        echo 'Fuzz run completed at' $$(date);
        sleep 10;
      done"

  # Interactive shell for debugging
  fuzz-shell:
    extends: fuzz
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    command: []

networks:
  fuzz-network:
    driver: bridge