version: '3.8'

services:
  fuzz-test:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: .docker/Dockerfile.fuzz
      platforms:
        - linux/amd64
    volumes:
      - ../:/app
    working_dir: /app
    command: zig build fuzz-compare --fuzz --port 8080
    ports:
      - "8080:8080"
    environment:
      - TERM=xterm-256color