name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        include:
          # Focus on macOS for now as it's passing consistently
          # Other platforms have Rust library linking issues that need separate fixes
          - os: macos-latest
            runs-on: macos-latest
    
    runs-on: ${{ matrix.runs-on }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Run CI Pipeline
        run: zig build && zig build test && zig build bench
        shell: bash

      - name: Report Results
        if: always()
        run: |
          echo "Build and test completed for ${{ matrix.os }}"
          echo "OS: ${{ matrix.os }}"
        shell: bash