name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/docs.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup

      - name: Generate Zig documentation
        run: |
          zig build docs
          mkdir -p ./docs-output
          cp -r zig-out/docs/* ./docs-output/ || true

      - name: Generate Rust documentation
        run: |
          cargo doc --all-features --no-deps
          cp -r target/doc/* ./docs-output/ || true

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: './docs-output'