name: Fuzz Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run fuzz tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  fuzz-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        zig-version: [0.14.0]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ matrix.zig-version }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        
    - name: Cache Zig
      uses: actions/cache@v3
      with:
        path: ~/.cache/zig
        key: ${{ runner.os }}-zig-${{ matrix.zig-version }}-${{ hashFiles('build.zig.zon') }}
        restore-keys: |
          ${{ runner.os }}-zig-${{ matrix.zig-version }}-
          
    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Build project
      run: zig build
      
    - name: Run fuzz tests
      run: |
        echo "Running fuzz tests..."
        
        # Run individual fuzz test components
        echo "Testing stack fuzz tests..."
        timeout 300 zig build fuzz-stack || echo "Stack fuzz tests completed/timed out"
        
        echo "Testing memory fuzz tests..."
        timeout 300 zig build fuzz-memory || echo "Memory fuzz tests completed/timed out"
        
        echo "Testing arithmetic fuzz tests..."
        timeout 300 zig build fuzz-arithmetic || echo "Arithmetic fuzz tests completed/timed out"
        
        echo "All fuzz tests completed"
        
    - name: Run comprehensive fuzz test suite
      run: |
        echo "Running comprehensive fuzz test suite..."
        timeout 600 zig build fuzz || echo "Comprehensive fuzz tests completed/timed out"
        
    - name: Report results
      if: always()
      run: |
        echo "Fuzz testing completed"
        echo "Check the logs above for any failures or crashes"
        echo "If tests timed out, this is expected for long-running fuzz tests"
        
    # Optional: Upload crash reports or interesting findings
    - name: Upload fuzz test artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: fuzz-test-results
        path: |
          zig-out/
          zig-cache/
        retention-days: 5